In [1]:
print("a")

a


merhaba buraya notlar alınıyor markdown ile

In [2]:
"a"

'a'

In [3]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [6]:
a * b

array([ 2,  6, 12, 20])

In [7]:
import numpy as np

In [8]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
a = np.array([1,2,3,4,5])

In [10]:
type(a)

numpy.ndarray

In [11]:
a

array([1, 2, 3, 4, 5])

In [12]:
np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

In [14]:
np.array([5.14,3,1.5,7], dtype = "int")

array([5, 3, 1, 7])

Sıfırdan array oluşturma

In [15]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((3,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [18]:
np.full((4,2),5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [19]:
np.arange(0,42,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [21]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [23]:
np.random.normal(10,4, (3,4))

array([[ 5.25002172,  5.84883178, 12.68941475, 16.92618142],
       [ 6.48053652, 14.22621738,  9.64818352, 13.93485114],
       [ 8.91990231,  9.14018821, 10.82389528,  6.64744358]])

In [24]:
np.random.normal(10,4,(3,4))

array([[16.03937133,  9.26071606, 11.92307382,  4.94638335],
       [13.97633626,  8.74133024, 12.91551458, 17.28264634],
       [ 4.06728999, 10.98584408,  8.78512449,  9.77166854]])

In [25]:
np.random.randint(0,10,(3,3))

array([[8, 4, 1],
       [3, 7, 9],
       [4, 9, 9]])

* **ndim**: _boyut sayısı_
* **shape**: _boyut bilgisi_
* **size**: _toplam eleman sayısı_
* **dtype**: _array veri tipi_

In [26]:
import numpy as np

In [27]:
np.random.randint(10, size = 10)

array([9, 8, 5, 7, 7, 3, 1, 6, 9, 6])

In [28]:
a = np.random.randint(10, size = 10)

In [29]:
a.ndim

1

In [30]:
a.shape

(10,)

In [31]:
a.size

10

In [33]:
a.dtype

dtype('int32')

In [34]:
b = np.random.randint(10, size = (3,5))

In [35]:
b

array([[7, 1, 4, 2, 6],
       [6, 2, 2, 4, 2],
       [2, 5, 9, 2, 3]])

In [36]:
b.ndim

2

In [37]:
b.shape

(3, 5)

In [38]:
b.size

15

In [39]:
b.dtype

dtype('int32')

Yeniden Şekillendirme

In [41]:
import numpy as np

In [42]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a = np.arange(1,10).reshape(1,9)

In [46]:
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
a.shape

(1, 9)

In [48]:
a.ndim

2

Array Birleştirme(Concatenation)

In [49]:
import numpy as np

In [50]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [52]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [53]:
z = np.array([7,8,9])

In [54]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

İki Boyut

In [56]:
a = np.array([[1,2,3],
            [4,5,6]])

In [57]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Array Ayırma(Splitting)

In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3,99,99,3,2,1])

In [5]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [6]:
a,b,c = np.split(x, [3,5])

In [7]:
a

array([1, 2, 3])

In [8]:
b

array([99, 99])

In [9]:
c

array([3, 2, 1])

In [10]:
#iki boyutlu ayırma
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.vsplit(m ,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [14]:
ust, alt = np.vsplit(m, [2])

In [15]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [21]:
ust, alt= np.hsplit(m, [2])

In [22]:
ust

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [23]:
alt

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [24]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [26]:
import numpy as np

In [39]:
v = np.array([2,1,7,8,5,3])

In [38]:
v

array([1, 2, 3, 5, 7, 8])

In [33]:
v.sort()

In [34]:
v

array([1, 2, 3, 5, 7, 8])

In [40]:
v

array([2, 1, 7, 8, 5, 3])

In [41]:
np.sort(v)

array([1, 2, 3, 5, 7, 8])

In [53]:
#iki boyutlu sıralama
m = np.random.normal(20,5, (3,3))

In [54]:
m

array([[20.48990212, 20.59874466, 15.79211404],
       [21.65507382, 28.71966514, 21.36757746],
       [24.29419271, 24.38572062, 17.33675701]])

In [55]:
np.sort(m,axis = 1)

array([[15.79211404, 20.48990212, 20.59874466],
       [21.36757746, 21.65507382, 28.71966514],
       [17.33675701, 24.29419271, 24.38572062]])

In [56]:
np.sort(m,axis=0)

array([[20.48990212, 20.59874466, 15.79211404],
       [21.65507382, 24.38572062, 17.33675701],
       [24.29419271, 28.71966514, 21.36757746]])

In [59]:
a = np.random.randint(10, size = 10)
a

array([0, 0, 0, 8, 7, 4, 2, 6, 8, 3])

In [60]:
a[0]

0

In [61]:
a[-1]

3

In [62]:
a[0] = 100

In [63]:
a

array([100,   0,   0,   8,   7,   4,   2,   6,   8,   3])

In [64]:
m =np.random.randint(10, size= (3,5))
m

array([[1, 5, 6, 9, 5],
       [7, 6, 3, 9, 3],
       [8, 0, 9, 9, 0]])

In [65]:
m[0,0]

1

In [66]:
m[2,2]

9

In [67]:
m[2,2]=2

In [68]:
m

array([[1, 5, 6, 9, 5],
       [7, 6, 3, 9, 3],
       [8, 0, 2, 9, 0]])

# Slicing İle Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [69]:
import numpy as np

In [70]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [71]:
a[0:3]

array([20, 21, 22])

In [72]:
a[:5]

array([20, 21, 22, 23, 24])

In [73]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [74]:
a[1::2]

array([21, 23, 25, 27, 29])

In [75]:
a[0::2]

array([20, 22, 24, 26, 28])

In [76]:
a[2::2]

array([22, 24, 26, 28])

In [77]:
a[0::3]

array([20, 23, 26, 29])

In [78]:
#İki Boyutlu Slice İşlemleri

In [79]:
m = np.random.randint(10, size =(5,5))

In [80]:
m

array([[3, 9, 5, 6, 1],
       [9, 6, 4, 2, 2],
       [4, 0, 5, 4, 9],
       [0, 2, 2, 0, 5],
       [5, 0, 4, 4, 8]])

In [83]:
m[:,0]

array([3, 9, 4, 0, 5])

In [84]:
m[:,2]

array([5, 4, 5, 2, 4])

In [85]:
m[0,:]

array([3, 9, 5, 6, 1])

In [86]:
m[3,:]

array([0, 2, 2, 0, 5])

In [87]:
m[0:2, 0:3]

array([[3, 9, 5],
       [9, 6, 4]])

In [88]:
m[:,:2]

array([[3, 9],
       [9, 6],
       [4, 0],
       [0, 2],
       [5, 0]])

In [89]:
m

array([[3, 9, 5, 6, 1],
       [9, 6, 4, 2, 2],
       [4, 0, 5, 4, 9],
       [0, 2, 2, 0, 5],
       [5, 0, 4, 4, 8]])

In [90]:
m[1:3, 0:2]

array([[9, 6],
       [4, 0]])

# Alt Küme Üzerinde İşlem Yapmak

In [91]:
import numpy as np

In [92]:
a = np.random.randint(10, size = (5,5))
a

array([[1, 1, 7, 8, 2],
       [6, 3, 2, 2, 5],
       [7, 3, 1, 9, 2],
       [8, 8, 9, 9, 3],
       [2, 7, 9, 2, 1]])

In [93]:
alt_a = a[0:3, 0:2]

In [94]:
alt_a

array([[1, 1],
       [6, 3],
       [7, 3]])

In [95]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [96]:
alt_a

array([[99999,     1],
       [    6,   888],
       [    7,     3]])

In [97]:
a

array([[99999,     1,     7,     8,     2],
       [    6,   888,     2,     2,     5],
       [    7,     3,     1,     9,     2],
       [    8,     8,     9,     9,     3],
       [    2,     7,     9,     2,     1]])

In [99]:
m =np.random.randint(10, size = (5,5))
m

array([[5, 5, 6, 4, 6],
       [5, 1, 9, 5, 0],
       [8, 3, 2, 3, 5],
       [8, 3, 9, 9, 1],
       [7, 7, 4, 5, 9]])

In [100]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[5, 5],
       [5, 1],
       [8, 3]])

In [101]:
alt_b[0,0] = 9999

In [102]:
alt_b

array([[9999,    5],
       [   5,    1],
       [   8,    3]])

In [103]:
m

array([[5, 5, 6, 4, 6],
       [5, 1, 9, 5, 0],
       [8, 3, 2, 3, 5],
       [8, 3, 9, 9, 1],
       [7, 7, 4, 5, 9]])

# Fancy Index İle Elemanlara Erişmek

In [106]:
import numpy as np
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [107]:
v[1]

3

In [108]:
v[3]

9

In [109]:
v[5]

15

In [110]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [111]:
al_getir = [1,3,5]

In [112]:
v[al_getir]

array([ 3,  9, 15])

In [113]:
#iki boyutta fancy

In [114]:
m = np.arange(9).reshape((3,3))

In [115]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [119]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [120]:
m[satir, sutun]

array([1, 5])

In [121]:
#basit index ile fancy index

In [122]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [123]:
m[0, [1,2]]

array([1, 2])

In [124]:
#slice ile fancy

In [125]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [126]:
import numpy as np
v = np.array([1,2,3,4,5])

In [127]:
v < 3

array([ True,  True, False, False, False])

In [128]:
v[v<3]

array([1, 2])

In [129]:
v[v>3]

array([4, 5])

In [130]:
v[v==3]

array([3])

In [131]:
v[v<=3]

array([1, 2, 3])

In [132]:
v[v>=3]

array([3, 4, 5])

In [133]:
v[v !=3]

array([1, 2, 4, 5])

In [134]:
v

array([1, 2, 3, 4, 5])

In [135]:
v*2

array([ 2,  4,  6,  8, 10])

In [136]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [137]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [138]:
v**2

array([ 1,  4,  9, 16, 25])

# Matematiksel İşlemler

In [139]:
import numpy as np
v = np.array([1,2,3,4,5])

In [141]:
v - 1

array([0, 1, 2, 3, 4])

In [142]:
v * 5

array([ 5, 10, 15, 20, 25])

In [143]:
v /5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [144]:
v*5/10 -1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [145]:
#ufunc

In [146]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [147]:
np.add(v , 1)

array([2, 3, 4, 5, 6])

In [148]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [149]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [150]:
v**2

array([ 1,  4,  9, 16, 25])

In [151]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [152]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [153]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [154]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [157]:
np.absolute(np.array([-3]))#mutlak değer

array([3])

In [158]:
np.sin(360)

0.9589157234143065

In [159]:
np.cos(180)

-0.5984600690578581

In [160]:
v = np.array([1,2,3])

In [161]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [162]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [163]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [164]:
?np

Type:        module
String form: <module 'numpy' from '/lib/python3.11/site-packages/numpy/__init__.py'>
File:        /lib/python3.11/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``he

In [165]:
#cheatsheet (kopya kağıdı)

# İstatistiksel hesaplamalar

In [168]:
np.mean(v, axis = 0)

2.0

In [169]:
v

array([1, 2, 3])

In [170]:
v.sum()

6

In [171]:
v.min()

1

In [172]:
v.max()

3

In [173]:
# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [174]:
import numpy as np

5*x0 + x1 = 12 

x0 + 3*x1 = 10

In [176]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [177]:
a

array([[5, 1],
       [1, 3]])

In [178]:
b

array([12, 10])

In [179]:
x = np.linalg.solve(a,b)

In [180]:
x

array([1.85714286, 2.71428571])

In [181]:
import numpy as np

np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [182]:
import numpy as np
np.subtract(v, 2)

array([-1,  0,  1])

In [187]:
import numpy as np
np.power(v, 3)

array([ 1,  8, 27], dtype=int32)

In [189]:
import numpy as np

np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])